export const services = [
    {
        slug: 'business-strategy',
        title: 'Business Strategy',
        iconName: 'Target',

        shortDesc: 'Partnering with leading-edge digital companies to expand our portfolio and pass on those services to our clients.',
        fullDesc: 'Partnering with some of the leading-edge digital companies allows us to expand our portfolio and pass on those services to our valued clients. Control over your international payments by providing you with the tools to collect, convert and pay money globally utilizing the digital economy.LNBG provides a streamlined and transparent PMT, Payment Management Tool, for businesses that need to send and receive international payments.LNBG provides you with your own dedicated IBAN for your business.Receive payments from your suppliers or cardholders',
        specialTitle: 'Compete Risk Free with $100,000 in Virtual Cash',
        challenge: 'Slowly we are losing control of where we can take your money. At LNBG we give you control back.',
        resultAndBenefits: `An open architectural platform enables us to offer services and counseling on a wide variety of institutions and investment products. This places
LNBG International Investment LLC is in an advanced position in objective counseling, compared to other market players.
LNBG International Investment will be in the International Market’s most active Independent institution on getting representation from international reputed investment firms. This allows our clients to reap the benefits of flexible global investment opportunities.`,
        image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Market Entry Planning', desc: 'Comprehensive analysis and execution roadmaps for entering new markets with confidence.' },
            { title: 'Competitive Positioning', desc: 'Deep competitor analysis to define and strengthen your unique market position.' },
            { title: 'Growth Roadmaps', desc: 'Long-term, milestone-driven plans aligned to your business objectives and resources.' },
            { title: 'Digital Partnerships', desc: 'Access to our network of leading-edge digital companies to expand your capabilities.' },
        ],
        stats: [{ value: '300+', label: 'Strategies Delivered' }, { value: '25+', label: 'Countries Covered' }, { value: '98%', label: 'Client Satisfaction' }],
    },
    {
        slug: 'asset-management',
        title: 'Asset Management',
        iconName: 'BarChart3',
        shortDesc: 'LNBIG INT INVESTMENT asset management services are built around portfolio management to optimise returns.',
        fullDesc: 'LNBIG INT INVESTMENTS offers comprehensive asset management services built around portfolio management, research and dealing, innovative product development, marketing, and distribution. We serve institutional investors, family offices, and high-net-worth individuals, offering bespoke investment solutions that balance risk and return across multi-asset portfolios.',
        specialTitle: 'Special Characteristics of the Asset Management',
        challenge: 'Like all investments, asset management requires careful portfolio construction and ongoing monitoring. But effective asset management offers diversification and the potential for upside performance, among other benefits. Our portfolios are meticulously designed and professionally managed to help reduce risk and enable strong investor returns.',
        resultAndBenefits: 'Long as investment is the largest and most trusted asset manager in the world, with more than $1.2 Billion in total assets under management. Our asset management services benefit from over 15 years of insight and experience. We offer a wide variety of portfolio solutions to help your investment meet your needs.',
        image: 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Portfolio Optimisation', desc: 'Dynamic asset allocation strategies to maximise risk-adjusted returns across market cycles.' },
            { title: 'Research & Analysis', desc: 'In-depth fundamental and quantitative research informing every investment decision we make.' },
            { title: 'Risk Management', desc: 'Robust frameworks to identify, measure, and manage portfolio risk at every level.' },
            { title: 'Performance Reporting', desc: 'Transparent, regular reporting giving you full visibility into your portfolio performance.' },
        ],
        stats: [{ value: '$1.2B+', label: 'Assets Under Management' }, { value: '15+', label: 'Years Track Record' }, { value: '92%', label: 'Retention Rate' }],
    },
    {
        slug: 'corporate-investments',
        title: 'Corporate Investments',
        iconName: 'Building2',
        shortDesc: 'LNBIG INT INVESTMENTS carries out highly selective investments in regions and entities where there is high potential.',
        fullDesc: 'LNBIG INT INVESTMENTS aim is to carry out highly selective investments in regions and entities where there is high potential for return. We focus on identifying and executing high-conviction opportunities across both public and private markets. Our team conducts exhaustive due diligence and works closely with management teams to ensure every investment is structured for long-term success.',
        specialTitle: 'Special Characteristics of the Corporate Investments',
        challenge: 'Like all investments, corporate investment requires careful due diligence and risk assessment. But effective corporate investing offers substantial upside performance potential and strategic value creation benefits. Our investment team is experienced in evaluating complex transactions and structuring deals that protect and grow capital.',
        resultAndBenefits: 'Long as investment is one of the most trusted corporate investment firms in the world, with a strong track record across more than 200 completed investments. Our corporate investment services benefit from over 20 years of deal-making experience. We offer a highly selective approach to ensure every investment generates significant value for our clients.',
        image: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Due Diligence', desc: 'Comprehensive financial, legal and operational analysis before any capital is deployed.' },
            { title: 'Value Creation', desc: 'Active partnership with management teams to drive operational and financial improvements.' },
            { title: 'Selective Approach', desc: 'High-conviction, concentrated investments in opportunities with clear upside potential.' },
            { title: 'Exit Strategy', desc: 'Disciplined exit planning to maximise returns at the optimal point in the investment cycle.' },
        ],
        stats: [{ value: '200+', label: 'Investments Made' }, { value: '40+', label: 'Sectors Covered' }, { value: '88%', label: 'Positive Exits' }],
    },
    {
        slug: 'markets-research',
        title: 'Markets Research',
        iconName: 'LineChart',
        shortDesc: 'For the past 25 years we have designed and implemented virtually every type of business research for hundreds of clients.',
        fullDesc: 'LNBIG INT INVESTMENTS for the past 25 years designed and implemented virtually every type of business research for hundreds of clients. Our research practice covers qualitative and quantitative methodologies, delivering actionable intelligence across industries, geographies, and market segments. We help clients understand consumer behaviour, competitive dynamics, and macroeconomic trends to inform smarter strategic decisions.',
        specialTitle: 'Special Characteristics of the Markets Research',
        challenge: 'Like all research, market research requires a disciplined approach and deep methodological expertise. But effective market research offers invaluable insight and competitive advantages, among other benefits. Our research engagements are meticulously designed and professionally executed to deliver reliable findings that inform high-stakes business decisions.',
        resultAndBenefits: 'Long as investment is the largest and most trusted research firm in the region, with more than 500 research projects delivered. Our markets research services benefit from over 25 years of insight and experience across 30+ sectors. We offer a wide variety of research methodologies to help your business get the answers it needs.',
        image: 'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Primary Research', desc: 'Custom surveys, interviews and focus groups designed to answer your specific business questions.' },
            { title: 'Sector Intelligence', desc: 'Deep-dive industry reports covering market size, trends, competitive landscape and forecasts.' },
            { title: 'Consumer Insights', desc: 'Behavioural and attitudinal research to understand what drives your target customers.' },
            { title: 'Macro Analysis', desc: 'Economic and geopolitical analysis to help you anticipate and navigate market shifts.' },
        ],
        stats: [{ value: '500+', label: 'Research Projects' }, { value: '25+', label: 'Years Experience' }, { value: '30+', label: 'Sectors Covered' }],
    },
    {
        slug: 'real-estate-investment',
        title: 'Real Estate Investment',
        iconName: 'HomeIcon',
        shortDesc: 'Strategic acquisition and development of commercial and residential assets to deliver strong risk-adjusted returns.',
        fullDesc: 'LNBIG INT INVESTMENTS real estate practice identifies and acquires high-quality commercial and residential assets across key global markets. A REIT Management Company (RMC) identifies a project and raises public money through an Initial Public Offering (IPO). We manage the full investment lifecycle — from sourcing and due diligence through to asset management and exit.',
        specialTitle: 'Special Characteristics of the Real Estate Investment',
        challenge: 'Like all investments, real estate investment carries risk and requires careful market analysis and property selection. But effective real estate investment offers diversification, income generation, and capital appreciation potential, among other benefits. Our real estate team is meticulously experienced and professionally networked to help reduce risk and enable strong investor returns.',
        resultAndBenefits: 'Long as investment is one of the most trusted real estate investment managers in the world, with more than $800 Million in total assets under management. Our real estate services benefit from over 18 years of market insight and experience. We offer a wide variety of real estate investment solutions to help your portfolio meet its objectives.',
        image: 'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Property Acquisition', desc: 'Identifying and securing prime commercial and residential properties at the right valuations.' },
            { title: 'Asset Management', desc: 'Active management to maximise income and capital appreciation from every asset we hold.' },
            { title: 'Development Finance', desc: 'Structuring development finance and joint ventures to bring high-potential projects to life.' },
            { title: 'REIT Management', desc: 'Public and private REIT structures providing investors with efficient access to real estate returns.' },
        ],
        stats: [{ value: '150+', label: 'Properties Acquired' }, { value: '$800M+', label: 'Portfolio Value' }, { value: '18+', label: 'Markets Active' }],
    },
    {
        slug: 'global-services',
        title: 'Global Services',
        iconName: 'Globe2',
        shortDesc: 'Partnering with leading-edge digital companies to expand our portfolio and pass on those services to clients globally.',
        fullDesc: 'LNBIG INT INVESTMENTS global services arm provides businesses with the infrastructure and expertise to operate successfully across international markets. From cross-border regulatory compliance to international trade facilitation, supply chain optimisation and foreign exchange management, we equip our clients with everything they need to scale globally with confidence.',
        specialTitle: 'Special Characteristics of the Global Services',
        challenge: 'Like all international operations, global business expansion requires navigating complex regulatory environments and market-specific challenges. But effective global services offer access to new markets and revenue streams, among other benefits. Our global team is meticulously experienced and professionally networked across 25+ countries to help clients succeed internationally.',
        resultAndBenefits: 'Long as investment is one of the most trusted global services providers, with operations spanning more than 25 countries and over 400 active global clients. Our global services benefit from deep local expertise combined with international capital markets knowledge. We offer round-the-clock support to help your business operate seamlessly across borders.',
        image: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'International Trade', desc: 'End-to-end trade facilitation covering documentation, logistics, finance and compliance.' },
            { title: 'Regulatory Compliance', desc: 'Expert guidance navigating the regulatory requirements of each jurisdiction you operate in.' },
            { title: 'FX Management', desc: 'Currency risk hedging and foreign exchange solutions to protect your international margins.' },
            { title: 'Global Network', desc: 'Access to our 25+ country partner network for on-the-ground local market intelligence.' },
        ],
        stats: [{ value: '25+', label: 'Countries Active' }, { value: '400+', label: 'Global Clients' }, { value: '24/7', label: 'Support Coverage' }],
    },
    {
        slug: 'bond-market',
        title: 'Bond Market',
        iconName: 'TrendingUp',
        shortDesc: 'Offering unrivalled bond market services to our clients as we follow evolving trends within the marketplace.',
        fullDesc: 'LNBIG INT INVESTMENTS offers bond market services to institutional and private investors seeking exposure to fixed income instruments. We combine deep credit research with an extensive dealer network to source the best execution for our clients. Whether you are seeking capital preservation, income generation, or portfolio diversification, our fixed income specialists structure the right solution.',
        specialTitle: 'Special Characteristics of the Bond Market',
        challenge: 'Challenge: LNBIG INT INVESTMENTS offers unrivalled services to our clients as we follow evolving trends within the marketplace and pursue measured growth. Like all investments, fixed income carries risk and requires careful credit selection and duration management. But effective bond market exposure offers income stability and portfolio diversification, among other benefits.',
        resultAndBenefits: 'Long as investment is one of the most trusted fixed income managers in the world, with more than $500 Million in bonds under management. Our bond market services benefit from over 20 years of fixed income insight and experience. We offer a wide variety of bond investment solutions to help your portfolio generate stable returns.',
        image: 'https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Fixed Income Strategy', desc: 'Bespoke fixed income portfolios built to match your income, duration and credit requirements.' },
            { title: 'Credit Research', desc: 'In-house fundamental credit analysis to identify value and manage default risk across the spectrum.' },
            { title: 'Primary Issuance', desc: 'Access to new bond issuances across investment grade, high yield and emerging market credits.' },
            { title: 'Secondary Trading', desc: 'Efficient execution across secondary bond markets through our broad network of counterparties.' },
        ],
        stats: [{ value: '$500M+', label: 'Bonds Managed' }, { value: '50+', label: 'Bond Issuers' }, { value: '99%', label: 'Execution Rate' }],
    },
    {
        slug: 'commodity-investments',
        title: 'Commodity Investments',
        iconName: 'Layers',
        shortDesc: 'LNBIG INT INVESTMENTS offers commodity investment in raw materials, agricultural products, and precious metals.',
        fullDesc: 'LNBIG INT INVESTMENTS offers commodity funds investment in raw materials or primary agricultural products, precious metals, such as gold and silver, energy resources, such as oil and natural gas, and agricultural goods, such as wheat.',
        specialTitle: 'Special Characteristics of the Commodities Market',
        challenge: 'Like all investments, commodity trading can carry risks. But commodities offer diversification and the potential for upside performance, among other benefits. BlackRock\'s commodity funds are meticulously designed and professionally managed to help reduce risk and enable strong investor returns.',
        resultAndBenefits: 'Long as investment is the largest and most trusted asset manager in the world, with more than $10 Billion in total assets under management. Our commodity funds benefit from over 20 years of insight and experience. We offer a wide variety of commodity funds to help your portfolio meet your needs.',
        image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
        galleryImages: [
            'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=600',
            'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
        ],
        features: [
            { title: 'Precious Metals', desc: 'Gold, silver and platinum exposure as a store of value and portfolio diversifier.' },
            { title: 'Energy Commodities', desc: 'Strategic positions in oil, gas and renewable energy commodities aligned to global trends.' },
            { title: 'Agricultural Products', desc: 'Investment in primary agricultural commodities benefiting from global food demand growth.' },
            { title: 'Commodity Funds', desc: 'Access to diversified commodity funds providing broad exposure with professional management.' },
        ],
        stats: [{ value: '8+', label: 'Commodity Classes' }, { value: '$300M+', label: 'Commodity AUM' }, { value: '85%', label: 'Annualised Returns' }],
    },
];

export function getServiceBySlug(slug) {
    return services.find((s) => s.slug === slug) || null;
}

export const footerQuickLinks = [
    { label: 'Commodity Investments', slug: 'commodity-investments' },
    { label: 'Bond Market', slug: 'bond-market' },
    { label: 'Global Services', slug: 'global-services' },
    { label: 'Real Estate Investment', slug: 'real-estate-investment' },
    { label: 'Markets Research', slug: 'markets-research' },
];
